fixed README.md file
domenico-siciliani/monaifl pull request #15
Opened 2021-11-24 15:47 UTC by tomaszwasowicz-digica

First attempt to fix the README.md file.

2021-11-25 07:13 UTC, domenico-siciliani approved these changes

2021-11-25 07:36 UTC, pawelpreczynski-digica commented
could you please try to use [automatically-numbered-list](https://stackoverflow.com/questions/12145232/create-an-automatically-numbered-list)?

2021-11-25 08:16 UTC, tomaszwasowicz-digica commented
Hey

Did you mean:

"Could WE please try to use ... " :D

Point 7.1 of:

https://docs.google.com/document/d/12r7B9mU_MEkZ0ABCrtiZZIFybSP3xFCMDliCm10LawM/edit#heading=h.8v695ab1q79a

And of course, YES WE CAN !

BR

On Thu, 25 Nov 2021 at 08:36, pawelpreczynski-digica <
***@***.***> wrote:

> could you please try to use automatically-numbered-list
> <https://stackoverflow.com/questions/12145232/create-an-automatically-numbered-list>
> ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/domenicosiciliani-digica/monaifl/pull/15#issuecomment-978911657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV5AFVRGDAVQIDF6HAP7IX3UNXRQJANCNFSM5IWMY3AQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-25 08:20 UTC, pawelpreczynski-digica commented
YES WE CAN! ;)

2021-11-25 13:56 UTC, pawelpreczynski-digica requested changes

2021-11-25 13:56 UTC, pawelpreczynski-digica commented on README.md
> +## 1. About The Project
Please also remove numbers here on headers.

2021-11-30 09:18 UTC, pawelpreczynski-digica approved these changes

2021-11-30 10:14 UTC, merged